### ISSUE TITLE
Use additionalProperties for all objects

### ISSUE THREAD

**Issue by estahn** [yannh/kubernetes-json-schema#5]
All objects should include `"additionalProperties": false,` to properly validate, e.g. the following should fail but doesn't with the current schemas:

```
resources:
  limits:
    foobar: 123
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

see https://github.com/instrumenta/kubernetes-json-schema/issues/29
